### ISSUE TITLE
New releases aren't in the registries

### ISSUE THREAD

**Issue by timwsuqld** [oscarhermoso/terraform-provider-binarylane#45]
I assume you are manually publishing releases to the Terraform Registry. Latest there is 0.8.1 (https://registry.terraform.io/providers/oscarhermoso/binarylane/latest). 

I believe there are Github actions to automate the publishing of new versions when you make a Github release.

It would also be great if you considered submitting it to the OpenTofu registry too (https://search.opentofu.org/docs/providers/adding)

**Comment by oscarhermoso** [comment]
Hi @timwsuqld ,

I'm not sure why v0.8.2 publish to the Terraform registry automatically... I am already using the GitHub actions recommeded by Hashicorp.

I manully synchronized by clicking a button on the Terraform website, it has now appeared.

https://registry.terraform.io/providers/oscarhermoso/binarylane/0.8.2

This provider has been added to the OpenTofu registry:

https://search.opentofu.org/provider/oscarhermoso/binarylane/latest

However, it is still showing latest release as v0.8.1, which is suprising because their registry picked picked up the v0.8.2 release five days ago:

https://github.com/opentofu/registry/blob/c470b6ed2d4d83986489a0ca50990d5393073a82/providers/o/oscarhermoso/binarylane.json#L4-L17

OpenTofu does have a warning banner on their website:

> This is the beta preview of the OpenTofu Registry Search. The data in this interface may not be up to date.

Regardless, I would recommend using Terraform for now, I have not performed any testing with OpenTofu.
